column_map:
  group_col: user_id
  history_col: history
  item_col: item_id
  label_col: click
  neg_col: neg
  user_col: user_id
inter:
  dev: data/recbench/${data.name}/valid
  filters:
    history:
    - 'lambda x: x'
  test: data/recbench/${data.name}/test
  train: data/recbench/${data.name}/train
item:
  inputs:
  - title@${lm}: 50
  ut: data/recbench/${data.name}/items
name: ${rbname}
user:
  truncate: 50
  ut: data/recbench/${data.name}/users
