$$import:
  - common/operators/item-null.yaml
  - common/predictors/din.yaml
name: DIN
meta:
  user: NullConcat
config:
  user_config:
    inputer_config:
      use_cls_token: false
      use_sep_token: false
    flatten: false
    max_pooling: false
