$$import:
  - common/predictor/din.yaml
name: DIN
meta:
  user: NullConcat
config:
  use_item_content: false
  hidden_size: ${hidden_size}$
  user_config:
    inputer_config:
      use_cls_token: false
      use_sep_token: false
    flatten: false
    max_pooling: false
