$$import:
  - common/operators/user-ada.yaml
  - common/predictors/dot.yaml
name: NAML
meta:
  item: CNN
config:
  use_item_content: true
  hidden_size: ${hidden_size}$
  item_hidden_size: ${item_hidden_size}$
  use_fast_eval: ${fast_eval:true}$
  item_config:
    dropout: 0.1
    kernel_size: 3
