$$import:
  - common/operators/user-attention.yaml
  - common/predictors/dot.yaml
name: NRMS
meta:
  item: Attention
config:
  use_item_content: true
  use_fast_eval: ${fast_eval:true}$
  hidden_size: ${hidden_size}$
  item_hidden_size: ${item_hidden_size}$
  item_config:
    num_attention_heads: ${num_item_heads:8}$
    inputer_config:
      use_cls_token: false
      use_sep_token: true
  user_config:
    num_attention_heads: ${num_user_heads:8}$
