meta:
  predictor: DCNv2
config:
  use_neg_sampling: false
  predictor_config:
    stacked_dnn_hidden_units: [ 1000, 1000, 1000 ]
    parallel_dnn_hidden_units: [ 1000, 1000, 1000 ]
    dnn_activations: ReLU
    dnn_dropout: 0.1
    dnn_batch_norm: false
    cross_num: ${cross_num:3}$
    model_structure: stacked_parallel
    use_low_rank_mixture: true
