meta:
  item: Llama${llama}
config:
  use_item_content: true
  use_fast_eval: ${fast_eval:true}$
  item_page_size: ${item_page_size:128}$
  item_hidden_size: 4096
  hidden_size: ${hidden_size}$
  item_config:
    tune_from: ${tune_from}$
    use_lora: ${use_lora:false}$
    lora_r: ${lora_r:null}$
    lora_alpha: ${lora_alpha:null}$
    inputer_config:
      use_cls_token: false
      use_sep_token: false
