meta:
  item: FastFormer
config:
  use_item_content: true
  use_fast_eval: ${fast_eval:true}$
  hidden_size: ${hidden_size}$
  item_hidden_size: ${item_hidden_size}$
  item_config:
    num_attention_heads: 16
    num_hidden_layers: 1
    inputer_config:
      use_cls_token: false
      use_sep_token: false