name: ${exp.mode}
dir: saving/${data.name}/${model.name}/${embed.name}-${exp.name}
log: ${exp.dir}/exp.log
mode: test
load:
  save_dir: ../${embed.name}-train_test
  epochs: null
  model_only: true
  strict: true
  wait: false
store:
  top: 1
  early_stop: 2
policy:
  epoch_start: 0
  epoch: 10
  lr: 0.005
  freeze_emb: false
  pin_memory: false
  batch_size: 512
  device: gpu
  n_warmup: 0
  check_interval: -2
metrics:
  - GAUC
  - MRR
  - NDCG@5
  - NDCG@10